language: ruby
rvm:
  - ruby-2.4.1
  - ruby-2.3.4
  - ruby-head
  - jruby-9.1.10.0
  - jruby-head
  - rubinius
branches:
  only:
    - master
before_install:
  - sudo apt-get update
  - sudo apt-get install iputils-ping
matrix:
  include:
    - rvm: rubinius-3.76
      env:
        - RUBYOPT="-rbundler/deprecate"
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius
sudo: required
dist: trusty
