language: ruby
rvm:
  - ruby-2.4.1
  - ruby-2.3.4
  - ruby-head
  - jruby-9.1.10.0
  - jruby-head
  - rbx-3
  - rbx-head
branches:
  only:
    - master
before_install:
  - sudo apt-get update
  - sudo apt-get install iputils-ping
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: rbx-head
sudo: required
dist: trusty
