language: ruby
rvm:
  - ruby-2.4.1
  - ruby-2.3.4
  - ruby-head
  - jruby-9.1.10.0
  - jruby-head
  - rubinius
  - rubinius-3.76
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rubinius
sudo: false
